### ISSUE TITLE
Feature request: Delete from disk

### ISSUE THREAD

**Issue by Tanath** [clementine-player/Android-Remote#102]
App is great! The only missing feature I really need is the ability to delete from disk, not just playlist.

**Comment by Asfaloth** [comment]
This won't be included due to security reasons. The app is not made for file manipulations and an attacker could easily use such a feature to remove random files from your computer.

**Comment by Tanath** [comment]
So implement a check to see if the file is in the music library.

**Comment by LukeOwncloud** [comment]
I agree that it is a security related issue. So the user should have to actively enable it in the options menu (just like for downloading). And even better: The files to be deleted could be moved to a trash folder (so the actually deleting has to be done manually by the user).
Your point about removing "random files from your computer" I do not understand. Of course only files from the library are deletable this way, as @Tanath points out.

**Comment by Komzar** [comment]
One more to this request. 
It will be really grate to seat on sofa and manage new list of music for example stored on the USB stick. Not in Library yet.
