### ISSUE TITLE
Feature request: compilation support

### ISSUE THREAD

**Issue by tylerswagar** [clementine-player/Android-Remote#104]
Being able to sort albums into Various Artists was one of the biggest reasons I went with Clementine to begin with, as a library with more than a few compilations can get cluttered fast, so I would appreciate very much if the same feature were on Android.  At present it takes at least thrice as long to thumb through the sea of awkward single-track artists using Clementine Remote, at which point I may as well get my lazy self off the couch and make a playlist.  If my mobile library were as trim as my desktop, I could sit for hours and commit to much larger bags of potato chips.

**Comment by Asfaloth** [comment]
Can you please tell me how the tracks should be grouped instead? albumartist?

**Comment by phoenix87ta** [comment]
That's how I sort my Clementine library.  I was going to suggest using whatever view is selected for the library on the Clementine application, although I don't know whether that's exposed to the network remote app or not.  Incidentally, I just got this thing, and it owns.

**Comment by amuttsch** [comment]
Duplicate of #44. Other grouping options will be implemented soon.
