### ISSUE TITLE
Make lyrics full-screen and resizable.

### ISSUE THREAD

**Issue by eloyesp** [clementine-player/Android-Remote#105]
Font-size of lyrics is not good on small devices, also, when rotating the device, it doesn't use the full width.

I think it will improve readability making it full-screen (not a dialog), and make it resizable. Is it possible. I've never played with java-android, but I can try to work on it with a few instructions.

Thanks.

**Comment by amuttsch** [comment]
Lyrics dialog uses a different font size since the usage of material dialogs. It should be more readable now.

Clementine Remote receives the lyrics in a formatted way, the verses are together. I cannot change the way the lyrics are formatted.
