### ISSUE TITLE
Add media keys to small notification

### ISSUE THREAD

**Issue by sabret00the** [clementine-player/Android-Remote#107]
There are no lockscreen media controls for Android 5.0 

http://developer.android.com/reference/android/app/Notification.MediaStyle.html

**Comment by Asfaloth** [comment]
I implemented this in v10. Have you extended the notification in order to show the controls?

**Comment by prescott66** [comment]
I can confirm bug too

**Comment by Asfaloth** [comment]
Still works for me. Please make a Screenshot of your lockscreen while being connected to clementine. 

On 5 January 2015 23:21:54 CET, "Dušan Kazik" <notifications@github.com> wrote:
>I can confirm bug too
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/clementine-player/Android-Remote/issues/107#issuecomment-68792738

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by sabret00the** [comment]
The one on the left is Clementine while the one on the right is Shuttle+

![collage_20150106143118875](https://cloud.githubusercontent.com/assets/203217/5629923/cbcc29ee-95b0-11e4-930c-ba16ee45a269.jpg)

**Comment by prescott66** [comment]
Here is my screenshot from nexus 4 (5.0.2 LRX22G)

![screenshot_2015-01-06-15-36-41](https://cloud.githubusercontent.com/assets/735265/5630067/9ad1c632-95ba-11e4-99d0-05794bdfdbbe.png)

**Comment by Asfaloth** [comment]
You have controls when you expand the notification. But I get your point, you want controls in the small notification.

**Comment by sabret00the** [comment]
Maybe it's an issue with my phone (stock LG G3) but I can't expand the notification, whether two finger slide down, two slide up, one slide down, two finger spread, two finger pinch. I just can't get it to expand at all.


     On Tuesday, 6 January 2015, 17:21, Andreas <notifications@github.com> wrote:
   

 You have controls when you expand the notification. But I get your point, you want controls in the small notification.—

**Comment by amuttsch** [comment]
Done with commit 46a4d97c063fdf693f5bfe2553c0a668e59f61bb
