### ISSUE TITLE
Certain filenames fail to queue (adding from library to playlist)

### ISSUE THREAD

**Issue by nigels-com** [clementine-player/Android-Remote#109]
I had trouble queuing this track, perhaps due to the "[]" or the "+" in the filename.
The issue repros 100%.

`/Users/nigels/Music/Amazon Music/Coldplay/Ghost Stories [+digital booklet]/01-08- A Sky Full Of Stars.mp3`

**Comment by nigels-com** [comment]
Indeed, all the tracks in this album have this problem.
Clementine 1.2.2, Mac OS X 10.9.5

**Comment by Morthawt** [comment]
Still happening. I emailed the developer and was instead met with a link to this github to make an issue here. But I see it was already documented mid January and still no fix. Not very promising.

**Comment by Morthawt** [comment]
Nice! When will the update be released?

**Comment by amuttsch** [comment]
Don't know yet. But you can use the latest build from here: http://builds.clementine-player.org/android/

Note: You need a daily Clementine build and it might not be as stable as the released versions. (Download here: http://builds.clementine-player.org)

**Comment by Morthawt** [comment]
Thanks. I uninstalled the old one, installed the latest from that link but when I try and connect it says please update clementine to 1.2.1 or later. Well I have 1.2.3 and it is not connecting.

**Comment by amuttsch** [comment]
You need the latest Clementine build from here:  http://builds.clementine-player.org (Note: They may not be stable)

**Comment by Morthawt** [comment]
Well I fulfilled the version requirement? I will try the new clementine but I don't want a buggy experience. I came to you about the bug because of having a bugy experience. :(
