### ISSUE TITLE
Feature Request: Sort albums by year

### ISSUE THREAD

**Issue by rdsqc22** [clementine-player/Android-Remote#114]
I love Clementine Remote- it's a superbly functional app, that does nearly everything I would like it to, except one thing. When I select an artist and add them to the current playlist, the albums are added in alphabetical order, rather than chronological order as on the desktop client.

When I listen to multiple albums by an artist, I like to listen to them chronologically, so that I can hear and appreciate how the artist develops over time. Would you consider adding this?

**Comment by bheckman13** [comment]
+1
