### ISSUE TITLE
Can't delete songs from playlist/complete playlist

### ISSUE THREAD

**Issue by Bombe20** [clementine-player/Android-Remote#123]
Clementine: Version 1.2.3-1072-g6ecd470
Remote App: v10.1-58-gdcda5d4

Deleting tracks from the playlist and the "delete playlist" function just doesn't do anything, the songs do NOT get deleted from the list and the list can NOT be cleared via remote app.

Tried the above mentioned versions as well as the latest releases from the clementines web sites home.

Regards
Bombe 20

**Comment by amuttsch** [comment]
Works perfectly fine for me. What OS are you using? Try running Clementine from console (or the debug build if you are on Win) and post the log here (via pastebin).

**Comment by Bombe20** [comment]
Tried with linux, works fine. 

Win 8.1 log will follow soon.

**Comment by amuttsch** [comment]
You can pipe the output to a file I think. Go to the Clementine install dir with the console and type `clementine.exe > log.txt` (If you get a permission error, pipe it to `C:\log.txt` for example)

**Comment by Bombe20** [comment]
All I get is an empty log.txt.
Using dev build 1103-gc822871 and 
"clementine.exe > X:\log.txt"

**Comment by amuttsch** [comment]
try `clementine.exe > X:\log.txt 2>&1`

**Comment by Bombe20** [comment]
Thank you, works great.

http://pastebin.com/nik97Pjz

**Comment by amuttsch** [comment]
Ok, found the issue and fixed it in Clementine. The buildbot is building the build (buildception), when it's done you can test if the issue is resolved. I'll post a comment when the build is up.

**Comment by Bombe20** [comment]
Wow, that was fast.
I will try the new build asap after it gets built.

**Comment by amuttsch** [comment]
Windows build 1104 is up, please report if the issue is fixed, thanks :)

**Comment by Bombe20** [comment]
You, sir, deserve a medal! Everythings fixed.

Except the installer stillt forgets the installation path as mentioned there:
https://github.com/clementine-player/Clementine/issues/4806

**Comment by amuttsch** [comment]
Awesome, thanks for the feedback :)

Regarding the installer, I have to do some tests when I'm on my windows maschine.

**Comment by Bombe20** [comment]
Good luck with the installer ;)
And thank you a lot for everything!

Regards
Bombe20
