### ISSUE TITLE
Convert before download

### ISSUE THREAD

**Issue by TheLastProject** [clementine-player/Android-Remote#129]
I save my music as FLAC on my PC. However, due to storage reasons, I'd much prefer Ogg Vorbis on my phone. It would be nice to be able to choose to convert songs to another format before downloading.

**Comment by sean-abbott** [comment]
+ 1

**Comment by amuttsch** [comment]
This is already implemented, you have to use a nightly build for Clementine as well as Clementine Remote to use this feature.
