### ISSUE TITLE
Opus support on Windows builds

### ISSUE THREAD

**Issue by rheart** [clementine-player/Android-Remote#140]
Clementine 1.2.3 Windows version currently cannot play Opus files (.opus), giving an error "Your GStreamer installation is missing a plug-in".
If I extract libgstopus.dll and libopus-0.dll from GStreamer SDK and put them into corresponding Clementine directories, Clementine will play the files.

**Comment by hatstand** [comment]
Try [Clementine 1.3RC2](https://builds.clementine-player.org/win32/release/ClementineSetup-1.3.0rc2.exe)

**Comment by Venryx** [comment]
Tried that release (1.3.0 RC 2). It has the same error.

I also tried 1.3.2 RC 1 (from the page you linked), and that version failed -- except not just on Opus files, it also failed on regular mp3 files.
