### ISSUE TITLE
Could not reach host

### ISSUE THREAD

**Issue by vindicatorr** [clementine-player/Android-Remote#142]
Clementine-qt5: 1.2.3-1505-gabc6370
```
Preferences->Network Remote
  Use a network remote control: Y
  Only allow connections from the local network: N
  Require authentication code: N
```
Computer iptables allows everything.
Ping computer IP from android terminal works.
Kodi's "Kore" remote control can contact and control my computer.
"ss -pan" shows clementine listening on tcp port 5500.

EDIT:
using android clementine v10.1 (installed today)

**Comment by hatstand** [comment]
If you use a branch you get to keep the pieces.

**Comment by vindicatorr** [comment]
@hatstand I have no idea what that is supposed to mean ("keep the pieces").

For my desktop (archlinux), I built the qt5 branch of Clementine.
For my smartphone, I installed Clementine remote control via Google Play.
The android remote is not finding clementine on my network (even when specifying my IP address).

I didn't know if that is something I would post under Google Play Reviews or here.

**Comment by hatstand** [comment]
If you use branches other than master don't expect things to work.
