### ISSUE TITLE
No sound on HTC One M8

### ISSUE THREAD

**Issue by grizzlii** [clementine-player/Android-Remote#144]
Your player is the best! I have tried just about every player on every platform. Clementine outperforms all. I am running it on an Ubuntu 14.04 server. I have installed Clementine Remote on my phone to access my library via my LAN. But I am unable to get it to produce sound on my phone or designated renderer.

I am connected to my host, have populated my library remotely. I can load/create playlists and play tracks. At least the progress bar says they are playing but no sound. Bluetooth is off and my renderer is set to my phone but no sound. I have now discovered that the sound is rendering to my host (in a different building), not to my phone. What is going on?

Also, UPnP/DLNA + Samba + rendering options would be great. I will send money for that!

**Comment by amuttsch** [comment]
With Clementine Remote you can control Clementine, but not stream the music from your computer to your phone. It is still played back on your PC.

**Comment by grizzlii** [comment]
So sad. I have LAN media servers and home media renderers. MediaMonkey can handle this but like other players they don't get shuffle right. I have tested just about every player on every platform. Clementine is the only one that has 'eliminate duplicates' AND seems to be able to play shuffle in genre and playlists. Guess I will have to get a Linux tablet with UPnP/DLNA/Samba. Will Clementine work on an Asus tablet running Android?
