### ISSUE TITLE
Crashing when attempting to Adjust EQ

### ISSUE THREAD

**Issue by Jimthetyreman** [clementine-player/Android-Remote#146]
Using Clementine in Mint 17.3 Cinnamon

Clementine 1.3 is crashing when I try to adjust EQ when playing tracks first. If I adjust one frequency and then start to play a track I can continue to adjust other frequencies.

**Comment by amuttsch** [comment]
Not a Clementine Remote problem, see here: https://github.com/clementine-player/Clementine/issues/4541
