### ISSUE TITLE
Clementine app crash on connect.

### ISSUE THREAD

**Issue by AlphaBootis** [clementine-player/Android-Remote#147]
The clementine app I downloaded from the play store crashes consistently when trying to connect it to my computer.
AFAIK i've got no weirdness going on, any information I could give to troubleshoot this?

I've got the latest version of Celementine running on Windows 10. (1.3.1)
I've got Huawei P8lite running on Android 5.0.1. (factory OS)
I've got a TP link router running OpenWRT.

Windows Firewall allows for connections. I've imposed no restrictions on internal network traffic.

**Comment by amuttsch** [comment]
I publish a new version later this week, please check if the problem is present in this version as well. If you don't want to wait you can install the latest nightly build from here: https://builds.clementine-player.org/android/

**Comment by AlphaBootis** [comment]
I side-loaded the latest version I could find in that directory and can confirm that fixed it!
