### ISSUE TITLE
Feature request: Support for high res screens

### ISSUE THREAD

**Issue by bfovez** [clementine-player/Android-Remote#159]
Clementine interface on my 3200x1800 screen is a mess.
See attached capture.
It is my understanding that it would involve to upagrade to Qt 5. By il will become more and more necessary nowadays.
![image](https://cloud.githubusercontent.com/assets/19409008/17744646/f9e38142-64a8-11e6-87a0-a72b0571bbdf.png)
![image](https://cloud.githubusercontent.com/assets/19409008/17744662/0fdb2f40-64a9-11e6-9974-17f93a214960.png)

**Comment by friederbluemle** [comment]
@bfovez You're in the wrong repo :) Please check here: https://github.com/clementine-player/Clementine
