### ISSUE TITLE
Feature Request: SAVE multiple IP Adresses 

### ISSUE THREAD

**Issue by hausaffe** [clementine-player/Android-Remote#160]
when you are using this app on multiple devices or networks, it would be nice if you wouldn't need to type the ip adress all over again

**Comment by gaga9999** [comment]
also network discovery would be nice, i.e. search subnet

**Comment by amuttsch** [comment]
The adresses are saved. When you enter the first few digits, you can select the ip.

Network discovery is already implemted and working.
