### ISSUE TITLE
Please allow Clementine Remote to be moved to external storage

### ISSUE THREAD

**Issue by bodidharma** [clementine-player/Android-Remote#166]
It would be nice to allow Clementine Remote to use and downlold to external SD Card. Please fix this.

**Comment by ZacharyDflores** [comment]
I thought it was a problem of permissions on my phone, it says "the folder is not writable". Please fix this. GREAT WORK! Congratulations

**Comment by hatstand** [comment]
Builds are here: https://builds.clementine-player.org/android/
