### ISSUE TITLE
Downloading playlist makes plasma-desktop/kdeinit4 go bonkers and gets canceled

### ISSUE THREAD

**Issue by alphapapa** [clementine-player/Android-Remote#39]
Ok, I know this is weird, but here is what is happening:

1.  I view a playlist on my phone.  (By the way, half the time it says "Playlist is empty!" and I have to try over and over again before it actually shows the songs in the playlist.)

2.  I click the Download Playlist button.

3.  plasma-desktop on my laptop goes into an infinite loop, using 60%+ CPU time, and constantly increasing its memory usage; it never releases this memory unless I kill and restart it.  It's completely unresponsive during this time.  kdeinit4 also seems to go bonkers, but it only use 30-40% CPU and doesn't increase memory usage.  This lasts 30+ seconds; sometimes it stops on its own, other times I have to kill plasma-desktop and restart it manually.

4.  When this happens, the remote app cancels the playlist download.  It seems to get through 3-4 songs at most before this happens.

Downloading individual songs seems to work.

This is happening every time I try.  Using KDE 4:4.11.3-0ubuntu0.1~ubuntu13.04~ppa1, Clementine 1.2.1-94-gb5ba116~raring, and remote app 8.4.

**Comment by amuttsch** [comment]
Is this still happening or can I close this one?

**Comment by alphapapa** [comment]
I haven't tried this in a long time, and I'm guessing it's obsolete by now.  If it happens again I'll report it again.  Thanks.
