### ISSUE TITLE
Library view needs sorting and grouping

### ISSUE THREAD

**Issue by alphapapa** [clementine-player/Android-Remote#44]
How many artists are in my music library?  I don't know; at least 1,086 according to $(ls ~/Music | wc -l).  But the remote app only displays the library by artist, resulting in a list that's so big it's useless.  And each item takes up so much screen space with the padding and "1 albums" underneath that I can only see 8 artists in the list at a time.  That would mean I'd have to scroll through 136 pages to see them all.

The library view needs grouping by genre, artist, album, year, etc. to be useful.  It also needs to be much more compact.  I don't need a separate line telling me how many albums by that artist exist in my library.

Here's what it looks like now: ![2013-12-19 16 20 39](https://f.cloud.github.com/assets/601365/1783875/a8d6dd5e-68c9-11e3-9576-1484862bc1c6.png)

Here's what it could look like: 
![2013-12-19 16 20 39 edited](https://f.cloud.github.com/assets/601365/1783989/76fba2ae-68cb-11e3-99dc-59e786967023.png)

**Comment by nigels-com** [comment]
Yeah, this would be my main request.  (I'll buy you Pizza anyway...)  I tend to prefer browsing by album (perhaps an old school CD-by-CD kind of mindset) and I really dislike how various artist and "featuring" tracks get sorted.  (For example: Daft Punk feat. Pharrell Williams - Get Lucky)

What would also be nice is navigating by recent Tracks, Artists or Albums.

**Comment by bmoore** [comment]
+1

**Comment by Daniel12344** [comment]
+2
i also prefer browsing by album. 
Or even by folder if this is possible. Help a lot if some files are not tagged correctly.

Maybe its also possible to add "add complete album to playlist" (sort by track number)
